-- =====================================================================
-- SCHEMA DE BANCO DE DADOS - FAMILY MONEY (SUPABASE POSTGRESQL)
-- Cole este script no SQL Editor do seu projeto Supabase e clique em RUN.
-- =====================================================================

-- 1. LIMPAR TABELAS EXISTENTES (SE HOUVER)
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS fixed_items CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS app_users CASCADE;
DROP TABLE IF EXISTS app_backups CASCADE;

-- 2. CRIAÇÃO DE TABELAS

-- Contas Bancárias
CREATE TABLE accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  balance numeric(12, 2) NOT NULL DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Categorias de Lançamentos
CREATE TABLE categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  icon text NOT NULL DEFAULT 'help-circle',
  color text NOT NULL DEFAULT '#6b7280',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Cartões de Crédito
CREATE TABLE cards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  closing_day integer NOT NULL CHECK (closing_day >= 1 AND closing_day <= 31),
  due_day integer NOT NULL CHECK (due_day >= 1 AND due_day <= 31),
  account_id bigint REFERENCES accounts(id) ON DELETE CASCADE NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Contas Fixas / Receitas Recorrentes
CREATE TABLE fixed_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text NOT NULL,
  amount numeric(12, 2) NOT NULL,
  day_of_month integer NOT NULL CHECK (day_of_month >= 1 AND day_of_month <= 31),
  type text NOT NULL CHECK (type IN ('income', 'expense')),
  account_id bigint REFERENCES accounts(id) ON DELETE CASCADE NOT NULL,
  category_id bigint REFERENCES categories(id) ON DELETE SET NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Usuários do Aplicativo
CREATE TABLE app_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text UNIQUE NOT NULL,
  password text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Backups do Aplicativo
CREATE TABLE app_backups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  data jsonb NOT NULL
);

-- Transações / Lançamentos Diários
CREATE TABLE transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text NOT NULL,
  amount numeric(12, 2) NOT NULL,
  date date NOT NULL,
  category_id bigint REFERENCES categories(id) ON DELETE CASCADE NOT NULL,
  payment_method text NOT NULL CHECK (payment_method IN ('account', 'card')),
  card_id bigint REFERENCES cards(id) ON DELETE CASCADE,
  installments integer NOT NULL DEFAULT 1,
  account_id bigint REFERENCES accounts(id) ON DELETE CASCADE,
  user_id bigint REFERENCES app_users(id) ON DELETE SET NULL, -- Vinculado à tabela app_users
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. INSERÇÃO DE DADOS INICIAIS (MOCK DATA)

-- Contas
INSERT INTO accounts (id, name, balance) VALUES
(1, 'Itaú Corrente', 5500.00),
(2, 'Nubank Poupança', 1200.00),
(3, 'XP Investimentos', 15000.00);

-- Categorias
INSERT INTO categories (id, name, icon, color) VALUES
(1, 'Moradia', 'home', '#8b5cf6'),
(2, 'Alimentação', 'shopping-cart', '#10b981'),
(3, 'Transporte', 'car', '#06b6d4'),
(4, 'Saúde', 'activity', '#ff3b30'),
(5, 'Educação', 'book-open', '#a855f7'),
(6, 'Lazer', 'smile', '#10b981'),
(7, 'Assinaturas & Serviços', 'credit-card', '#3b82f6'),
(8, 'Outros', 'help-circle', '#6b7280');

-- Cartões
INSERT INTO cards (id, name, closing_day, due_day, account_id) VALUES
(1, 'Nubank Roxinho', 25, 2, 2),
(2, 'XP Visa Infinite', 10, 17, 3),
(3, 'Itaú Click', 5, 12, 1);

-- Contas Fixas
INSERT INTO fixed_items (id, description, amount, day_of_month, type, account_id, category_id) VALUES
(1, 'Salário Alexandre (Pai)', 9500.00, 30, 'income', 1, NULL),
(2, 'Salário Mariana (Mãe)', 6200.00, 5, 'income', 2, NULL),
(3, 'Aluguel & Condomínio', 3800.00, 10, 'expense', 1, 1),
(4, 'Escola Beatriz', 1200.00, 8, 'expense', 1, 5),
(5, 'Plano de Saúde Familiar', 950.00, 15, 'expense', 3, 4),
(6, 'Energia / Água / Gás', 450.00, 20, 'expense', 1, 1);

-- Usuários Iniciais do Aplicativo
INSERT INTO app_users (id, name, email, password) VALUES
(1, 'Fábio (Pai)', 'fbdv1202@gmail.com', '123'),
(2, 'Joyce (Mãe)', 'joycesiqueirafs@gmail.com', '123'),
(3, 'Filha (Beatriz)', 'filha@familia.com', '123');

-- Transações Recentes
-- NOTA: Como não temos os UUIDs de autenticação criados ainda, o campo user_id inicia como NULL
INSERT INTO transactions (id, description, amount, date, category_id, payment_method, card_id, installments, account_id, user_id) VALUES
(1, 'Geladeira Nova', 1800.00, '2026-07-02', 1, 'card', 2, 6, NULL, NULL),
(2, 'Seguro Auto', 1200.00, '2026-07-28', 3, 'card', 1, 4, NULL, NULL),
(3, 'Supermercado Semanal', 450.00, '2026-08-01', 2, 'account', NULL, 1, 2, NULL),
(4, 'Combustível Carro', 150.00, '2026-08-02', 3, 'account', NULL, 1, 1, NULL);

-- Ajustar a sequência de auto-incremento de cada tabela (importante no Postgres)
SELECT setval('accounts_id_seq', (SELECT MAX(id) FROM accounts));
SELECT setval('categories_id_seq', (SELECT MAX(id) FROM categories));
SELECT setval('cards_id_seq', (SELECT MAX(id) FROM cards));
SELECT setval('fixed_items_id_seq', (SELECT MAX(id) FROM fixed_items));
SELECT setval('transactions_id_seq', (SELECT MAX(id) FROM transactions));
SELECT setval('app_users_id_seq', (SELECT MAX(id) FROM app_users));

-- Habilitar leitura pública ou configurar RLS se necessário. 
-- Para fins de facilidade inicial, as tabelas estarão sem Row Level Security (RLS) habilitado.
-- Se desejar ativar segurança por usuário depois, habilite o RLS no console do Supabase.
ALTER TABLE accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE cards DISABLE ROW LEVEL SECURITY;
ALTER TABLE fixed_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_backups DISABLE ROW LEVEL SECURITY;
